name: Django image build
on:
  push:
    branches: [ "main","master" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          no-cache: true
          push: true
          tags: |
            tusharjain25/taskapp:${{ steps.commit.outputs.short }}
            tusharjain25/taskapp:latest